#cloud-config
ssh_pwauth: true
disable_root: false
chpasswd:
  expire: false
  users:
    - name: root
      password: password
      type: text

packages:
  - stress-ng

write_files:
  - path: /opt/stress_ng_random_vm.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      # A simple script to simulate bursty CPU and memory consumption in cycles

      # Check if stress-ng is installed
      if ! command -v stress-ng &> /dev/null; then
          echo "Error: stress-ng is not installed. Please install it first."
          exit 1
      fi

      # Function to generate a random number between min and max
      random_range() {
          local min=$1
          local max=$2
          echo $(( min + RANDOM % (max - min + 1) ))
      }

      # Default settings
      BURST_MIN=5               # Minimum burst duration in seconds
      BURST_MAX=600             # Maximum burst duration in seconds
      ACTIVE_PROBABILITY=50     # Probability (%) that a VM will be active in a cycle
      CPU_LOAD_MIN=50           # Minimum CPU load percentage
      CPU_LOAD_MAX=100          # Maximum CPU load percentage
      CPU_CORES=$(nproc)        # Number of CPU cores to use
      MEM_WORKERS=1             # Number of memory workers
      MAX_MEM_PERCENT=80        # Percentage of total memory to use

      # generate a random range of memory percentage
      MEM_PERCENT=$(random_range 20 $MAX_MEM_PERCENT)

      # Calculate memory to use based on system total memory
      TOTAL_MEM=$(free -m | awk '/^Mem:/{print $2}')
      MEM_TO_USE=$(( TOTAL_MEM * MEM_PERCENT / 100 ))

      echo "Starting bursty workload simulation (running forever)"
      echo "Using $CPU_CORES CPU cores"
      echo "Memory usage: $MEM_TO_USE MB ($MEM_PERCENT% of system memory)"
      echo "VM activity probability: $ACTIVE_PROBABILITY%"
      echo ""

      # Run forever
      cycle=1
      while true; do
          # Generate random parameters for this cycle
          duration=$(random_range $BURST_MIN $BURST_MAX)
          cpu_load=$(random_range $CPU_LOAD_MIN $CPU_LOAD_MAX)

          # Determine if VM will be active this cycle (random probability)
          active_roll=$(random_range 1 100)
          if [ "$active_roll" -le "$ACTIVE_PROBABILITY" ]; then
              # VM is active - run stress
              echo "Cycle $cycle: ACTIVE - Running stress test for $duration seconds..."
              echo "  - CPU: $cpu_load%"
              echo "  - Memory: $MEM_TO_USE MB (aggressive, vm-keep)"

              stress-ng --cpu $CPU_CORES --cpu-load $cpu_load --vm $MEM_WORKERS --vm-bytes ${MEM_TO_USE}M --vm-keep --aggressive --timeout ${duration}s > /dev/null 2>&1
          else
              # VM is inactive - just idle for the duration
              echo "Cycle $cycle: IDLE - Sleeping for $duration seconds..."
              sleep $duration
          fi
          ((cycle++))
      done

  - path: /etc/systemd/system/stress-workload.service
    permissions: '0644'
    content: |
      [Unit]
      Description=Bursty stress-ng workload simulator
      After=network.target

      [Service]
      Type=simple
      ExecStart=/opt/stress_ng_random_vm.sh
      Restart=always
      RestartSec=5

      [Install]
      WantedBy=multi-user.target

runcmd:
  - sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
  - sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
  - systemctl restart sshd
  - ["systemctl", "daemon-reload"]
  - ["systemctl", "enable", "--now", "stress-workload.service"]
