apiVersion: v1
kind: Service
metadata:
  name: ssh-{SVC_NAME_SUFFIX}-{VM_BASENAME}-{BATCH_ID}
  namespace: {vm-ns}
  labels:
    batch-id: "{BATCH_ID}"
    vm-basename: "{VM_BASENAME}"
spec:
  type: {SVC_TYPE}
  selector:
    kubevirt.io/domain: {VM_BASENAME}
  ports:
  - name: ssh
    protocol: TCP
    port: 22          # Cluster internal port
    targetPort: 22    # The SSH port inside the VM guest OS
{SSH_NODEPORT_LINE}
