apiVersion: v1
kind: Service
metadata:
  name: svc-{SVC_NAME_SUFFIX}-{VM_BASENAME}-{BATCH_ID}
  namespace: {vm-ns}
  labels:
    batch-id: "{BATCH_ID}"
    vm-basename: "{VM_BASENAME}"
spec:
  type: {SVC_TYPE}
  selector:
    kubevirt.io/domain: {VM_BASENAME}
  ports:
  - name: tcp-{SVC_PORT}
    protocol: TCP
    port: {SVC_PORT}
    targetPort: {SVC_TARGET_PORT}
{SSH_NODEPORT_LINE}
